### ISSUE TITLE
the proper key-binding to send the code and eval them

### ISSUE THREAD

**Issue by t-cool** [t-cool/jscl-playground#3]
What do you think is the proper key-binding for send the code and eval them?

Now we use "Cmd-e", but it catches google search on Chrome(Windows).

**Comment by asciian** [comment]
I have a opinion about this topic. Shortcuts function is unusable for STEM products because some of them use the computer which doesn’t have keyboards. For example, iPad is used in some schools. We should improve button UI rather than improving them. However we can overwrite key with event listener of key down events . We have no problem about using Cmd-E.

iPhoneから送信

2018/02/09 12:05、t-cool <notifications@github.com>のメール:

**Comment by t-cool** [comment]
Thanks! 

As for improving button UI, I have an idea too.   My idea is to translate blocks into JSCL code and do some animations on the browser. [Blocky](https://blockly-demo.appspot.com/static/demos/interpreter/step-execution.html) is an option for it. I'd like to make a program like as scratch using JSCL.

As to the shortcut key(Cmd-e), could you overwrite key with event listener of key down events?
Then the Windows users will be able to use Ctl-e without any worries.
